"""images table

Revision ID: 190f068ae5aa
Revises: 27f676ee434b
Create Date: 2018-09-04 20:55:11.072053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190f068ae5aa'
down_revision = '27f676ee434b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_timestamp'), 'uploaded_files', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_timestamp'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
